unpackaged/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Closed</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Deceased</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Significant_Other__c/Significant_Other__c.object-meta.xml
<CustomObject>
    <label>Significant Other</label>
    <nameField>
        <displayFormat>SO-{00000000}</displayFormat>
        <label>Significant Other ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Significant Others</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Significant_Other__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Client</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Client</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Significant Others</relationshipLabel>
    <relationshipName>Significant_Others</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Significant_Other__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Contact?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Significant_Other__c/fields/Relationship_Status__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Status__c</fullName>
    <label>Relationship Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Significant_Other__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Son</fullName>
            </value>
            <value>
                <fullName>Guardianship Care and Protection Order</fullName>
            </value>
            <value>
                <fullName>Former partner or Ex partner</fullName>
            </value>
            <value>
                <fullName>Stepfather</fullName>
            </value>
            <value>
                <fullName>Stepmother</fullName>
            </value>
            <value>
                <fullName>Brother-in-law</fullName>
            </value>
            <value>
                <fullName>Sister-in-law</fullName>
            </value>
            <value>
                <fullName>Brother</fullName>
            </value>
            <value>
                <fullName>Sister</fullName>
            </value>
            <value>
                <fullName>Uncle</fullName>
            </value>
            <value>
                <fullName>Aunt</fullName>
            </value>
            <value>
                <fullName>Grandfather</fullName>
            </value>
            <value>
                <fullName>Grandmother</fullName>
            </value>
            <value>
                <fullName>Foster Father</fullName>
            </value>
            <value>
                <fullName>Foster Mother</fullName>
            </value>
            <value>
                <fullName>Friend/Neighbour - male</fullName>
            </value>
            <value>
                <fullName>Friend/Neighbour - female</fullName>
            </value>
            <value>
                <fullName>Other relative - male - not listed elsewhere</fullName>
            </value>
            <value>
                <fullName>Other relative - female - not listed elsewhere</fullName>
            </value>
            <value>
                <fullName>Son-in-Law</fullName>
            </value>
            <value>
                <fullName>Daughter-in-Law</fullName>
            </value>
            <value>
                <fullName>Daughter</fullName>
            </value>
            <value>
                <fullName>Father</fullName>
            </value>
            <value>
                <fullName>Mother</fullName>
            </value>
            <value>
                <fullName>Husband/Male Partner</fullName>
            </value>
            <value>
                <fullName>Wife/Female Partner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/CME_TestDataFactory.cls
public class CME_TestDataFactory{

    public static Account createAccount(string recordTypeName,String fName, String lName,String email){
    
        Account acc= new Account();
        Id recTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get(recordTypeName).getRecordTypeId();
        
        if(recordTypeName == 'Client'){
            acc.RecordTypeID=recTypeId ;
            acc.FirstName=fName;
            acc.LastName=lName;
            acc.personMailingStreet = 'TestStreet';
            acc.personMailingCity = 'TestCity';
            acc.personMailingState= 'TestState';
            acc.personMailingCountry = 'Australia';
            acc.personMailingpostalCode = '12345';
            acc.PersonEmail=email;
        }
        else{
            acc.RecordTypeID=recTypeId ;
            acc.Name = lName;
        }
        return acc;
    }
    
    public static Event createEvent(string whatId,String subject,String status, String Type,dateTime startDT, dateTime endDT){
    
        Event objE= new Event();
        objE.whatId = whatId;
        objE.subject = subject;
        objE.Status__c = status;
        objE.StartdateTime = startDT;
        objE.EnddateTime = endDT;
        objE.Type = type;
        return objE;
    }
    
    public static Significant_Other__c createSignificantOther(string clientId,boolean isPrimary){
    
        Significant_Other__c objCR= new Significant_Other__c();
        objCR.Client__c = clientId;
        objCR.First_name__c = 'testFname';
        objCR.Last_name__c = 'testLastName';
        objCR.Relationship_Status__c = 'Active';
        objCR.Type__c = 'Son';
        objCR.Primary_Contact__c = isPrimary;
        return objCR;
    }
    
    
   
}